### ISSUE TITLE
Error running python3 -m pynlp

### ISSUE THREAD

**Issue by angoodkind** [sina-al/pynlp#2]
When I run the command above, I get the error:
```
adamg:~ adamg$ python3 -m pynlp
/usr/local/opt/python3/bin/python3.5: Error while finding spec for 'pynlp.__main__' (<class 'ImportError'>: No module named 'corenlp_protobuf'); 'pynlp' is a package and cannot be directly executed
```

I have set my `CORE_NLP` variable, and started a new Terminal session.

**Comment by sina-al** [comment]
Hi angoodkind,
Thanks for pointing this out. I've updated the setup file to include module dependencies.

**Comment by angoodkind** [comment]
I also needed to install corenlp-protobuf. That should be in the README

**Comment by sina-al** [comment]
Hi angookind.
I had attempted to address this issue with [this commit.](https://github.com/sina-al/pynlp/commit/581923b460da9e44aa8fd24a9beaf23ef6ef00f4) Thank you for bringing it up. The problem arose because I forgot to specify  the dependent modules in `setup.py`. From this version `pynlp=0.3.4.2` onwards, calling `pip3 install pynlp` should automatically install all the required dependencies. Try installing the latest version and let me know if it still doesn't work.

**Comment by angoodkind** [comment]
Thanks. The previous version worked after running `pip3 install corenlp-photobuf`. I'd prefer not to uninstall and reinstall.

**Comment by angoodkind** [comment]
Did this update inadvertently change something else? I'm now getting an import error when using `from pynlp import StanfordCoreNLP`. 

When I try
```
import pynlp
pynlp.StanfordCoreNLP(...)
```
it says that the module `pynlp` has no attribute `StanfordCoreNLP`

**Comment by sina-al** [comment]
> Did this update inadvertently change something else? I'm now getting an import error when using from pynlp import StanfordCoreNLP.
> 
> When I try
> 
> import pynlp
> pynlp.StanfordCoreNLP(...)
> it says that the module pynlp has no attribute StanfordCoreNLP

Hi angoodkind, 
Thanks for bringing this up. I'm not entirely sure why this is happening.

**Comment by angoodkind** [comment]
Thanks, I tried to delete that comment. Stupid mistake on my part.
